server.port: 8082

spring:
#  main:
#    allow-bean-definition-overriding: true
  application:
    name: order-service
  config:
    import:
      - optional:nacos:seata-client.yaml
  cloud:
    nacos:
      server-addr: localhost:8848

    sentinel:
      transport:
        dashboard: localhost:9090
      web-context-unify: false
      datasource:
#        flow:
#          nacos:
#            server-addr: localhost:8848
#            data-id: order-service-flow-rules
#            group-id: SENTINEL_GROUP
#            data-type: json
#            rule-type: flow
#        #降级规则
#        degrade:
#          nacos:
#            server-addr: localhost:8848
#            data-id: ${spring.application.name}-degrade-rules
#            group-id: SENTINEL_GROUP
#            data-type: json
#            rule-type: degrade
        paramFlow:
          nacos:
            server-addr: localhost:8848
            data-id: ${spring.application.name}-param-rules
            group-id: SENTINEL_GROUP
            data-type: json
            rule-type: param_flow
    openfeign:
      client:
        config:
          default:
            logger-level: headers
            connect-timeout: 5000
            read-timeout: 100000
            request-interceptors:
              - com.loserico.cloud.feign.interceptor.IdempotentInterceptor
          order-service:
            request-interceptors:
              - com.loserico.cloud.sentinel.auth.AuthFlowInterceptor
    loadbalancer:
      retry:
        enabled: true
        max-retries-on-same-service-instance: 3
        max-retries-on-next-service-instance: 1
        retry-on-all-operations: false
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/tlmall_order?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&useCompression=true&useUnicode=true&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false
      username: cloud2023
      password: 123456
      initial-size: 10
      min-idle: 10
      max-active: 500
      max-wait: 60000
      validation-query: SELECT 1
      validation-query-timeout: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      keep-alive: false
      filters: stat,wall
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 1800000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: -1


hibernate.query.mode: loose
hibernate.query.cache: true
hibernate.jdbc.batch_size: 100

management.endpoints.web.exposure.include: '*'
loser:
  mvc:
    rest-exception-advice-enabled: false