server:
  port: 0
  
management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: awesome-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
