server:
  port: 8081
  
management:
  endpoints:
    web:
      exposure:
        include: '*'

##这是默认的负载均衡策略, ribbon是顶级配置项, 不在spring:下面    
#ribbon:
#  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#
spring:
  application:
    name: portal-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        metadata:
          version: 1.0.0
    loadbalancer:
      enabled: true
      eager-load:
        clients:
          - awesome-service
#          - storage-service
