server.port: 8081

spring:
  profiles:
    active: dev
  application:
    name: portal-service
  config:
    import:
      - optional:nacos:boot-common.yaml
      - nacos:portal-service.yaml
      - nacos:portal-service-${spring.profiles.active:}.yaml
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        metadata:
          version: 1.0.0
#      config:
#        file-extension: yaml
    loadbalancer:
      eager-load:
        clients:
          - awesome-service
      retry:
        enabled: true
        max-retries-on-same-service-instance: 3
        max-retries-on-next-service-instance: 1
    sentinel:
      transport:
        dashboard: localhost:9090
    openfeign:
      compression:
        request:
          enabled: true
          mime-types: text/plain,text/xml,application/xml,application/json
          min-request-size: 3
        response:
          enabled: true
      httpclient:
        hc5:
          pool-concurrency-policy: strict
          pool-reuse-policy: fifo
        max-connections: 200
        max-connections-per-route: 50
      client:
        config:
          default:
            logger-level: HEADERS