server:
  port: 8081
  
management:
  endpoints:
    web:
      exposure:
        include: '*'

##这是默认的负载均衡策略, ribbon是顶级配置项, 不在spring:下面    
#ribbon:
#  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#
spring:
  profiles:
    active: prod
  application:
    name: portal-service
  config:
    import:
      - nacos:portal-service.yaml
      - "nacos:portal-service-${spring.profiles.active:}.yaml"
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      discovery:
        metadata:
          version: 1.0.0
      config:
        file-extension: yaml
    loadbalancer:
      enabled: true
      eager-load:
        clients:
          - awesome-service
#          - storage-service
