server:
  port: 8081
  
management:
  endpoints:
    web:
      exposure:
        include: '*'

##这是默认的负载均衡策略, ribbon是顶级配置项, 不在spring:下面    
#ribbon:
#  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#
spring:
  profiles:
    active: prod
  application:
    name: portal-service
  config:
    import:
      - nacos:portal-service.yaml
      - "nacos:portal-service-${spring.profiles.active:}.yaml"
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      discovery:
        metadata:
          version: 1.0.0
      config:
        file-extension: yaml
    loadbalancer:
      eager-load:
        clients:
          - awesome-service
      retry:
        enabled: true
        max-retries-on-same-service-instance: 3
        max-retries-on-next-service-instance: 0
    openfeign:
      httpclient:
        hc5:
          pool-concurrency-policy: strict
          pool-reuse-policy: fifo
        max-connections: 200
        max-connections-per-route: 50
      client:
        config:
          default:
            logger-level: full
            connect-timeout: 1000
            read-timeout: 3000
          awesome-service:
            request-interceptors:
              - com.loserico.cloud.interceptor.IdempotentInterceptor